name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Zip the build artifacts
      run: zip -r build.zip dist/
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      run: |
        aws s3 cp build.zip s3://${S3_BUCKET}/build.zip

    - name: Connect to EC2 and deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION_EC }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/mykey.pem
        cat /tmp/mykey.pem
        chmod 400 /tmp/mykey.pem
        ssh -i "/tmp/mykey.pem" ec2-user@ec2-3-10-225-226.eu-west-2.compute.amazonaws.com
          sudo yum update -y
          sudo yum install -y httpd unzip
          sudo systemctl start httpd
          sudo systemctl enable httpd
          aws s3 cp s3://${S3_BUCKET}/build.zip build.zip
          sudo mkdir -p /var/www/html/dist
          sudo unzip -o build.zip -d /var/www/html/dist/
          sudo chmod -R 755 /var/www/html/dist
          sudo systemctl restart httpd
